apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-quota-metrics
  namespace: geneva
spec:
  selector:
    matchLabels:
      knicknic.github.io/name: azure-quota-metrics
  template:
    metadata:
      labels:
        knicknic.github.io/name: azure-quota-metrics
    spec:
      containers:
      - name: metrics
        # # Uncomment out below to specify client secret
        # env:
        # - name: AZURE_TENANT_ID
        #   value: <USER SPECIFIED AZURE_TENANT_ID **UPDATE VALUE**>
        # - name: AZURE_CLIENT_ID
        #   value: <USER SPECIFIED AZURE_CLIENT_ID **UPDATE VALUE**>
        # - name: AZURE_CLIENT_SECRET
        #   value: <USER SPECIFIED AZURE_CLIENT_SECRET **UPDATE VALUE**>
        image: knicknic/azure-quota-metrics
        imagePullPolicy: Always
        args:
        - "--subscription"
        - "abcdef01-0123-0123-0123-0123456789ab"
        - "--location"
        - "WestUS"
        - "--location"
        - "EastUS"
        - "--arm-limit"
        - "Microsoft.Network/trafficManagerProfiles=200"
        securityContext:
          privileged: false        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
