apiVersion: v1
kind: Service
metadata:
  name: azure-quota-metrics
spec:
  selector:
    knicknic.github.io/name: azure-quota-metrics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080